import type { Metadata } from 'next';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import Head from 'next/head';
import AxiosInterceptor from '@/api/AxiosInterceptor';
import StyledToast from '@/styles/common/ToastStyles';
import MainHeader from '@/components/common/layout/MainHeader';

export const metadata: Metadata = {
  title: 'Hufting',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/src/app/favicon.ico" />
      </Head>
      <body className="m-0 p-0">
        <div className=" top-0 bottom-0 right-0 left-0 fixed ">
          <div className=" h-full w-full max-h-full flex justify-center bg-white">
            <StyledComponentsRegistry>
              <div className="flex flex-col items-center bg-white max-w-[390px] w-full h-full">
                <MainHeader />
                <div className="w-full flex-grow overflow-y-auto overflow-x-hidden">
                  <AxiosInterceptor>
                    {children}
                    <StyledToast />
                  </AxiosInterceptor>
                </div>
              </div>
            </StyledComponentsRegistry>
          </div>
        </div>
      </body>
    </html>
  );
}
